### ISSUE TITLE
train_fully_supervised_2D_VIM.py

### ISSUE THREAD

**Issue by mhzhang1101** [ziyangwang007/Mamba-UNet#15]
Following your steps, during the mamba-unet training process, the result is 0 on the validation data set

**Comment by ziyangwang007** [comment]
Hi,

I cannot help you at this stage.

because: 
(1) Only limited information you provided, I have no idea if a people just say I got '0' .
(2) Many of my friends and people have already reproduced the code, and got a reasonable result.
(3) Even there is a very low-performance model, and the model is initialized without training, the dice coefficient/accuracy/hd/asd cannot be '0'.

I recommend you check the code again, and if you need more help or want to colloborate with me, i am happy to connect with you via email.

Thanks again for your interests.
